Repository developmentseed/obstore, pull requests merged in 2025-09, with the labels that each got.

#551 chore(obstore): Remove Arrow wrappers in favor of `pyo3-arrow::export` variants
  obstore/src/list.rs
Labels: chore

#563 feat: Build Python wheels for Python 3.14
  .github/workflows/wheels.yml
Labels: feat

#558 docs: Use dictionary syntax for list properties
  docs/cookbook.md
Labels: docs
