Repository developmentseed/obstore, pull requests merged in 2025-05, with the labels that each got.

#464 ci: Verify that PR titles follow conventional commits
  .github/workflows/conventional-commits.yml
Labels: ci

#465 fix: Raise error when passing credential provider with http url
  obstore/python/obstore/store.py
  tests/store/test_from_url.py
Labels: fix

#467 chore: Add yaml schema for pytest-mypy plugin
  tests/obspec/test-store.yml
Labels: chore

#470 docs: stream-zip example
  DEVELOP.md
  docs/examples/stream-zip.md
  examples/stream-zip/.gitignore
  examples/stream-zip/.python-version
  examples/stream-zip/README.md
  examples/stream-zip/main.py
  examples/stream-zip/pyproject.toml
  examples/stream-zip/uv.lock
  mkdocs.yml
Labels: docs

#473 chore: Update Rust lockfile
  Cargo.lock
  Cargo.toml
Labels: chore

#474 chore: test compatibility with obspec 0.1.0-beta.6
  pyproject.toml
  uv.lock
Labels: chore

#472 feat: Improve NASA Earthdata credential providers
  .github/workflows/test-python.yml
  docs/api/auth/earthdata.md
  obstore/python/obstore/auth/_http.py
  obstore/python/obstore/auth/earthdata.py
  obstore/python/obstore/auth/planetary_computer.py
  pyproject.toml
Labels: feat
